### ISSUE TITLE
(18-03-158 ESOL Open House) Email messages about contact info and web

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#182]
@curtiskphsc Could we look at highlighting summer camps and open house in a hero or card? Also, I think we need to find a better way to display the camps. Are these programs? If so, would it be appropriate to add them to the programs / career path?

---------------
From: Wendy Villa
Sent: Thursday, April 26, 2018 03:54 PM
To: Cielo Johnson; Webmaster
Cc: Ed Goolsby; Lucy Miller; Bonnie Mason; Alysen Heil
Subject: Fw: (18-03-158 ESOL Open House) Email messages about contact info and web
 
Hi Cielo, 

I was just talking with Karen about the CARDS on the website for the summer camps?  Do you think we can do the same thing for our upcoming ESOL night? It is scheduled for May 31st on Spring HIll campus?

Let me know if this is a possibility.  I believe they have it on the event calendar already.  

Thanks,

Wendy A. Villa

Recruiter/Promoter Specialist

Workforce Development

Pasco-Hernando State College

(727) 816-3244

**Comment by curtiskphsc** [comment]
@C13L0 That is a discussion that includes more than just me, but here is one concern raised regarding the use of cards for events.
1. These are events and thus would be displayed at the same time as the card or hero, and the card or hero would link to the event. First, it would be weird to have duplicate content on the home page. Second, I think the recommendation was, for ADA compliance, to not have the same link on a page twice.
To answer your second question, they are not academic programs and as a result (question 3) should not be on the programs page.
They used to have a summer career camp page. The issue was, it never got updated until a couple weeks or so before the new camps were to start. Thus, the page had outdated, worthless content on it 10-11 months out of the year.
Currently, the summer camp press release is on the front page, and as the events get closer they will roll to the front page. Also, they can use the event page link to drive traffic to. That is what we do and it works well.

**Comment by C13L0** [comment]
From: Karen Strouthopoulos
Sent: Friday, April 27, 2018 02:34 PM
To: Webmaster
Cc: Wendy Villa
Subject: Re: Summer Camp Promotional Advertising
 
Hello Cielo,


We appreciate the addition of "PHSC Offers Summer Career Camps" under the PHSC News Header on the webpage, which takes you to the Summer Camp press release.  However, there is no direct link to our registration page - is that something that can be added?  The page ends with..."contact Wendy Villa with her telephone and email address.  The students will need the registration link in order to register and pay online.


Thank you,

Karen


Karen Strouthopoulos

Senior Office Assistant

Workforce Programs

**Comment by C13L0** [comment]
@curtiskphsc 

From: Karen Strouthopoulos
Sent: Friday, April 27, 2018 02:34 PM
To: Webmaster
Cc: Wendy Villa
Subject: Re: Summer Camp Promotional Advertising
 
Hello Cielo,


We appreciate the addition of "PHSC Offers Summer Career Camps" under the PHSC News Header on the webpage, which takes you to the Summer Camp press release.  However, there is no direct link to our registration page - is that something that can be added?  The page ends with..."contact Wendy Villa with her telephone and email address.  The students will need the registration link in order to register and pay online.


Thank you,

Karen


Karen Strouthopoulos

Senior Office Assistant

Workforce Programs

**Comment by C13L0** [comment]
@jeppy64 I'm going to move this ticket to Phase II to add summer camps to the site

**Comment by curtiskphsc** [comment]
@C13L0  All they need to do is provide the registration link to the information center. They can add it to the event page and I can add the link to the news piece as well. We simply need them to provide us the link.

**Comment by curtiskphsc** [comment]
@C13L0 I have made that request of Wendy.

**Comment by Computerrat** [comment]
@curtiskphsc 
Is this ticket completed? Please let me know and I will close it out. Thanks.
