### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#194]
From: Wendy Villa
Sent: Thursday, May 3, 2018 10:09 AM
To: Webmaster
Cc: Ed Goolsby; Alysen Heil
Subject: Subdomain
 
Hi Cielo,

I would like to request that Workforce be added to the department list on our Phsc website, and a "Subdomain" be created to include information regarding Workforce, and the STEM initiative.

Please let me know what you'll need from me to get this taken care of.

Thanks so much for your help.

Sincerely,

Wendy A. Villa

Recruiter/Promoter Specialist

Workforce Development

Pasco-Hernando State College

(727) 816-3244

**Comment by C13L0** [comment]
@curtiskphsc 

> I would like to request that Workforce be added to the department list on our Phsc website

https://phsc.edu/about-phsc/departments

**Comment by curtiskphsc** [comment]
@C13L0 Awaiting a response.
"Wendy,
In order to add Workforce Development to the list of departments here https://phsc.edu/about-phsc/departments we need to identify a general contact phone number, fax number (if your office has one), and if possible an email (a general email, not employee specific). If Workforce Development does not have a general email, such as admissions@phsc.edu, I would suggest requesting one through IT. Using individual employee emails on a page such as this can be problematic as employees change jobs. Having a general department email avoids having outdated contact info out there if an employee moves on.

I have a Workforce Development number in the printed directory—727-816-3301 Is this the number you want listed?
Fax line:?
Contact email:?

Thank You,
Kevin"

**Comment by curtiskphsc** [comment]
@C13L0 Created a Workforce Development listing https://phsc.edu/node/2350 but I have no way to designate the campus.

**Comment by C13L0** [comment]
@curtiskphsc Navigate to "Manage Campus" in the admin dashboard, then choose directory listings tab.

![image](https://user-images.githubusercontent.com/3138019/40388185-cc006dce-5ddc-11e8-8bdf-dc9a4cf3d3de.png)

**Comment by curtiskphsc** [comment]
@C13L0 Okay, created Workforce listing. I would like to know if we can make an adjustment to the way the hours display when we select "closed". As it stands, selecting closed on Friday in the listing displays the word "closed" but still displays the hours for that day. It looks as if we are open _before_ 8 am and _after_ 4;30 pm. It would be nice if the hours for that day were automatically hidden when we select closed.
![hours-issue](https://user-images.githubusercontent.com/28155245/40440473-2fbbd09c-5e8c-11e8-912b-6d842ec76c22.JPG)

**Comment by C13L0** [comment]
@curtiskphsc Please create a new ticket for the above request as it has nothing to do with a subdomain request. We also need Marketing to provide a comp for the above request so it can be themed.
________

Closing this ticket, duplicate subdomain request in ticket Medical Scribe Project #295
