### ISSUE TITLE
Content Moderation Issue

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#212]
I received an email notification from admissions.phsc.edu that content needed to be reviewed (attached) 
![issue-with-moderation](https://user-images.githubusercontent.com/28155245/39997232-3265b6fc-5750-11e8-8d4d-56791c3e64c6.JPG)
The dashboard states I have nothing to review in moderation (attached)
![issues-with-content-moderation-2](https://user-images.githubusercontent.com/28155245/39997327-85cc0058-5750-11e8-88d2-89b4ed65511a.JPG)

**Comment by C13L0** [comment]
@jeppy64 

Can you please take a look at this view?  This report is not showing all items in moderation. It should be showing (https://admissions.phsc.edu/node/217/latest) in "Needs review" and an event in "Draft". Only the draft is showing.


![image](https://user-images.githubusercontent.com/3138019/40386607-373175fc-5dd8-11e8-9140-32fc6c8a202b.png)

**Comment by jeppy64** [comment]
Turns out in core 8.5 a bunch of things were changed and added for the better. What we built "at the time" was taking advantage of new table relationships, but starting from the node table, then joining out to the revisions table. "using the core views option for moderation state" gave us way too many false positives.

To show what's new in core 8.5, I created a brand new view that does begin in the correct table, joins correctly to revisions, states, node and historical data. "The stuff we didn't have available until now.

https://admissions.phsc.edu/admin/manage/content-revisions

Troubleshooting and time to complete: 2 hours

**Comment by jeppy64** [comment]
Updated to show only newest revisions. Applied to all sites. Disabled original view and updated menu link.
Time to complete: 1 hour

**Comment by C13L0** [comment]
@curtiskphsc Please give this a test at https://admissions.phsc.edu/admin/manage/content-moderation

It should be working properly now!

**Comment by C13L0** [comment]
@jeppy64 This has been approved and signed off on

**Comment by C13L0** [comment]
Closing
