### ISSUE TITLE
"Unable to send email" notice

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#245]
![email-notice-issue](https://user-images.githubusercontent.com/28155245/40383972-3c2fd402-5dd0-11e8-89eb-d17783251dc5.JPG)

**Comment by C13L0** [comment]
@curtiskphsc This is the same as #192 . I'm not able to replicate it and believe it is an issue with authenticating to Office 365, which is out of my control.

![email](https://user-images.githubusercontent.com/3138019/40384371-54cea24e-5dd1-11e8-9dd5-b5b1e89a6498.png)

**Comment by curtiskphsc** [comment]
@C13L0 No problem. You asked me to let you know is all. Who should be notified?

**Comment by C13L0** [comment]
@curtiskphsc When the issue is persistent and can be replicated. The drupal settings don't change and are solid. The issue is that O365 is not consistent and sometimes authenticates and other times it doesn't. In ticket #192 it was a persistent issue that affected all sites. Rick went in and reset the password to the no-reply email account.

**Comment by C13L0** [comment]
@curtiskphsc 
To recap an issue you brought up during our meeting yesterday,

When the website displays that an email cannot be sent, this shows that the website is working properly and as expected. An outgoing email message can be displayed for the following reasons.

* An email is trying to be sent to someone who is no longer an employee
* When the website cannot connect to ldap (as per previous explanations above)
