### ISSUE TITLE
Alumni Update Link

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#365]
Hi Cielo,

I believe at one point there was a link on the alumni page for alumni to submit news or updates. I am almost positive the link was on the right side of the page with "Distinguished Alumni Nomination Form" when we switched to the new website. For some reason the link for alums to submit updates is not there anymore and the Perspective that was just mailed out has a blurb in the alumni section encouraging alums to visit the website and submit their news or updates. Can you help me with this? 

Thank you,

Michelle

Michelle Bullwinkel

Director of Alumni and Donor Relations

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

(727) 816-3212

**Comment by C13L0** [comment]
From: Webmaster
Sent: Wednesday, August 22, 2018 10:39 AM
To: Michelle Bullwinkel
Subject: Re: Alumni Update Link
 
Hi Michelle,


I found the old webform at https://dev-phcc.pantheonsite.io/alumni


In order to create a new webform, please let me know any changes to the questions and which ones are mandatory. Also, I need the email address for all submissions.



Thanks,

Cielo

**Comment by C13L0** [comment]
From: Webmaster
Sent: Monday, August 27, 2018 01:17 PM
To: Michelle Bullwinkel
Subject: Re: Alumni Update Link | 365 | Awaiting further info
 
Hi Michelle,


As a reminder, we are still waiting on the following information to complete your request.


I found the old webform at https://dev-phcc.pantheonsite.io/alumni

In order to create a new webform, please let me know any changes to the questions and which ones are mandatory. Also, I need the email address for all submissions.




Thanks,

Cielo

**Comment by C13L0** [comment]
From: Michelle Bullwinkel
Sent: Monday, August 27, 2018 02:58 PM
To: Webmaster
Subject: Re: Alumni Update Link | 365 | Awaiting further info
 
Hi Cielo,


Thank you for following up on this. Below are the edits I would like to see made.


First sentence in paragraph above questions - "PHSC is interested in recognizing the achievements of our alumni." (instead of "its alumni")
Can we make Degree and Program two separate fields?
Sentence under Clubs and organizations - "Enter any clubs or organizations in which you were a member."

The email address the submissions should be sent to is alumni@phsc.edu. Please let me know if you have any questions.

Thank you,
Michelle

**Comment by C13L0** [comment]
Completed
