### ISSUE TITLE
Scheduled Webform Not Displaying To Anonymous Users

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#386]
We have an important event coming up for Rao Musunuru, M.D. and we scheduled the campus event RSVP webform to open immediately as described in the UI, and to close on a specific date. The webform is not displaying to anonymous users who are currently attempting to RSVP for this event.

https://phsc.edu/node/3042

![rao-musunuru-event-webform-not-working](https://user-images.githubusercontent.com/28155245/44467578-36ce6f00-a5f1-11e8-8cb7-b61e2b40d2e1.JPG)

**Comment by C13L0** [comment]
@curtiskphsc This webform hasn't been configured. Please provide the following: 

1. Webform submission email address
2. Confirmation email name and email address

**Comment by curtiskphsc** [comment]
@C13L0 
Submission email address: foundation@phsc.edu

Confirmation email name: Pasco-Hernando State College Foundation

Confirmation email address: foundation@phsc.edu

Don't we need a blurb of copy for the confirmation email? If so, please use the following.

Thank you for your submission and we look forward to visiting with you at the dedication of the Rao Musunuru, M.D. Conference Center. This event is being held at the Pasco-Hernando State College Spring Hill Campus located at 450 Beverly Ct, Spring Hill, FL 34606 on Tuesday, September 25, 2018, beginning at 4:30 p.m.

**Comment by C13L0** [comment]
@curtiskphsc This has been completed. Webforms are designed to be used on many events so there not static messages, they are all token based.

**Comment by C13L0** [comment]
From: Courtney Boettcher
Sent: Thursday, August 23, 2018 08:21 AM
To: Webmaster
Cc: Kevin Curtis; Lucy Miller
Subject: Web Form Request -- Fw: Your Dedication of the Rao Musunuru, M.D. Conference Center Registration
 
Good morning,


Thank you for resolving the web form visibility issue for the Dedication RSVP. I tested the form this morning as I wanted to see the reply.


Could you please add the word "the" before the event name, so that the sentence reads -- Thank you for your RSVP to the Dedication of the Rao Musunuru, M.D. Conference Center.


If the word "the" is will be part of all RSVP forms going forward, that is fine. Most event instances would need this word included.


Many thanks,

Courtney


Courtney Boettcher

Associate Director, Marketing and Communications

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

boettcc@phsc.edu

727.816.3738

**Comment by C13L0** [comment]
Completed
