### ISSUE TITLE
Peace Week Site Ticket Request

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#402]
Hi Cielo,

Student Life and Leadership would like to request a Peace Week website (similar to what we had for SLR)

Here is the link on our site now: https://student-life.phsc.edu/programs/peace-week

Peace Week \| Student Lifestudent-life.phsc.edu© 2018 Pasco-Hernando State College. All rights reserved. This website displays best in Chrome, Edge, Firefox, and Safari web browsers.
--

Kind Regards,

Laura Kelly Raposa

Coordinator of Student Life and Leadership

PHSC - Porter Campus at Wiregrass Ranch

Phone: 813.527.6676

Email: raposal@phsc.edu

Fax: 813.527.6993

**Comment by C13L0** [comment]
From: Laura Raposa
Sent: Tuesday, August 28, 2018 09:26 AM
To: Webmaster
Cc: John Fey; Jessica White
Subject: Re: Peace Week site
 
Hi Cielo,


Good morning!


I have attached the general schedule for this year's Peace Week at each campus.  I have separated everything by campus because I think that would be the easiest way to convey all the information.  


Also, do you think we could use a different icon for each campus?  If so, I'll chose one and send over.  I'd like to also "feature" the presentations done by the monks, Erin Daum and Bikers Against Child Abuse.  We do have general mission statements and purpose for Peace Week as well, so I can certainly fill in that text as we get closer to launching the site.


Finally, John is available to spend some face-to-face time with you this week if you need more specific information and I'll also be at West Campus on Thursday.  Hopefully this helps with the direction we all want to go, but let me know if you need additional information.  


Kind Regards,

Laura Kelly Raposa

Coordinator of Student Life and Leadership

PHSC - Porter Campus at Wiregrass Ranch


Phone: 813.527.6676

Email: raposal@phsc.edu

Fax: 813.527.6993

**Comment by C13L0** [comment]
From: Laura Raposa
Sent: Tuesday, August 28, 2018 02:13 PM
To: Webmaster
Cc: John Fey; Jessica White
Subject: Re: Peace Week site | 402 | Open
 
Cielo,


Seperating by campus would be preferred. Thanks!


Kind Regards,

Laura Kelly Raposa

Coordinator of Student Life and Leadership

PHSC - Porter Campus at Wiregrass Ranch


Phone: 813.527.6676

Email: raposal@phsc.edu

Fax: 813.527.6993

From: Webmaster
Sent: Tuesday, August 28, 2018 1:36:34 PM
To: Laura Raposa
Cc: John Fey; Jessica White
Subject: Re: Peace Week site | 402 | Open
 
Hi Laura,


The Peace Week website build will be the same as the SLR website. There is not a way to customize the site. I can separate the schedule either by Day or by Campus. Please let me know which is preferred.


Thanks,

Cielo

**Comment by C13L0** [comment]
From: Lucy Miller
Sent: Wednesday, August 29, 2018 11:39 AM
To: Jessica White
Cc: Corey Long; Courtney Boettcher; Kevin Curtis; Webmaster; Melanie Waxler
Subject: Re: Peace week colors
 
Hi Jessica,


We were moving away from Drupal 7 to Drupal 8 in order to be 100 percent ADA compliant.   We also have IMM #1-24 that specifies that web page creation need to be submitted for approval to:  

Department Head

Appropriate VP, provost or dean

Marketing Office

Webmaster


Currently, the subdomain you'd like to update is not consistent with our current website branding and is in Drupal 7, a concern because of the Office of Civil Rights complaint received last year. 

Why not use the Peace Week page on student-life.phsc.edu, as you did for SLR?  Mobile friendliness should not be an issue in Drupal 8. 


Lucy

Lucy Miller
Executive Director,
Marketing & Communications
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3448
FAX: 727-816-3723
millerl@phsc.edu





From: Jessica White
Sent: Wednesday, August 29, 2018 11:06 AM
To: Lucy Miller
Cc: Corey Long; Courtney Boettcher; Kevin Curtis; Webmaster
Subject: Re: Peace week colors
 
No, we are creating a page for the event, that is also mobile friendly, like the All College Day and SLR pages.


https://leadership-retreat.phsc.edu 

Thank you!

Jess  :)

Jessica M. White, MS

Director of Student Life & Leadership

Pasco-Hernando State College

o: 727.816.3764

c: 813.748.9202
From: Lucy Miller
Sent: Wednesday, August 29, 2018 11:04:15 AM
To: Jessica White
Cc: Corey Long; Courtney Boettcher; Kevin Curtis; Webmaster
Subject: Re: Peace week colors
 
Hi Jessica,


The theming and color palette area already set on the Student Life subdomain.   . . . So you're creating a Peace Week event page for your Student Life subdomain, just adding  new information? 



https://student-life.phsc.edu/programs/peace-week






Peace Week | Student Life
student-life.phsc.edu
© 2018 Pasco-Hernando State College. All rights reserved. This website displays best in Chrome, Edge, Firefox, and Safari web browsers.



Lucy Miller
Executive Director,
Marketing & Communications
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3448
FAX: 727-816-3723
millerl@phsc.edu





From: Jessica White
Sent: Tuesday, August 28, 2018 10:42 AM
To: Lucy Miller
Subject: Fw: Peace week colors
 
Lucy, 


Can you please clarify if the items we place on the websites need to be our colors or not?



Thank you!

Jess  :)

Jessica M. White, MS

Director of Student Life & Leadership

Pasco-Hernando State College

o: 727.816.3764

c: 813.748.9202


From: Webmaster
Sent: Tuesday, August 28, 2018 10:30 AM
To: Karen Kielar; John Fey; Laura Raposa; Jessica White
Subject: Re: Peace week colors
 
The website colors should complement the theme you are using in the design. This has nothing to do with college colors.

From: Karen Kielar
Sent: Tuesday, August 28, 2018 9:59:40 AM
To: Webmaster; John Fey; Laura Raposa; Jessica White
Subject: Peace week colors
 
Cielo,

Here are the colors for the Peace Week website. I don't understand why I need to send colors for campus events. We have been instructed that all campus events have to use the school colors which don't change.


k.


Karen Kielar

Graphic Artist

Student Life & Leadership

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654


P: 727.816.3442  F: 727.816.3208

**Comment by C13L0** [comment]
From: Robert E Bade
Sent: Wednesday, August 29, 2018 05:30 PM
To: Jessica White; Webmaster
Subject: Re: Peace Week website
 
Jessica, Cielo,


We invest a lot of resources into Peace Week - deservedly so because it has been an excellent and very well attended program in past years.


I approve to do the web site as we have done in past to assure another successful Peace Week. 


Bob

**Comment by C13L0** [comment]
@curtiskphsc @boettcc The approval documentation for the Student Leadership Retreat website is in ticket #169.

**Comment by C13L0** [comment]
From: Webmaster
Sent: Tuesday, September 4, 2018 02:42 PM
To: Robert E Bade; Jessica White; John Fey; Karen Kielar; Laura Raposa
Subject: Re: Peace Week website | 402 | In progress
 
Good afternoon,


This is a friendly reminder that the following items are missing:


**Event Information**  
Short description 

**Session Legend** - Max of 6
File type: .svg

**Colors** - Max of 4
In order to maintain a cohesive color palette throughout the website, colors should complement the logo and background images.



Please give me a call if you have any questions!

Cielo

**Comment by C13L0** [comment]
From: Laura Raposa
Sent: Tuesday, September 4, 2018 03:54 PM
To: Webmaster; Robert E Bade; Jessica White; John Fey; Karen Kielar
Subject: Re: Peace Week website | 402 | In progress
 
Hi Cielo,

Here is a short description for the event:
Each year we pause to recognize that peace is not simply the absence of war, but a constantly changing and fragile ideology that can be threatened if people are not given the opportunity to express themselves and connect with one another.  Despite worldwide volatility and political pressures, we must in our increasingly diverse and technologically advanced society, constantly seek understanding and global perspective. 

I have attached some icons for the session legend to this email.  My preference would be painting palette for Artists, Head with gears for Speakers, Drum for Drum Circle, Thumbs Up for the Monks. Let me know if there is a different vector image that I can refer to.  

The map on the site should direct to Spring Hill Campus.

Black, White, Gold and Blue for the colors. 

Let me know if you need anything else or if this information is incorrect.  Thanks for assisting me with all the questions in this process 😊

Kind Regards,
Laura Kelly Raposa
Coordinator of Student Life and Leadership
PHSC - Porter Campus at Wiregrass Ranch

**Comment by jeppy64** [comment]
@C13L0 

Reconfigured data model for campus driven sessions grouped by event day. Updated all views, dashboard and aliases. Removed 5 content types no longer applicable.

Time to complete: 5 hours

**Comment by C13L0** [comment]
From: Laura Raposa
Sent: Wednesday, September 12, 2018 2:12 PM
To: John Fey; Cielo Johnson
Subject: Re: Peace week url login

Hashtag: #phscpeaceweek

Website URL: peaceweek.phsc.edu (waiting on Marketing approval/call from Courtney)

Map Information: The monks will be creating a mandala at the Spring Hill campus only this year.  Peace Week is being offered at all five PHSC campuses.  For more information on campus locations, click here: https://phsc.edu/about-phsc/campuses (can I do that?

Sponsors: We do not have sponsors for this event.  Is it possible to remove this component?

Other than the marketing approval, I think that it may be ready to roll?

Kind Regards,
Laura Kelly Raposa
Coordinator of Student Life and Leadership
PHSC - Porter Campus at Wiregrass Ranch
 
Phone: 813.527.6676
Email: raposal@phsc.edu
Fax: 813.527.6993

**Comment by curtiskphsc** [comment]
@C13L0 @boettcc Why are we not using the Student Life subdomain? Seems like a huge loss of potential website traffic. In the past 30 days the Student Life page has had 1200 page views and the events page alone has had 936 page views with 587 of those categorized as unique. Why on earth would we send these visitors to a subdomain that would get used once yearly and then contain stale content, easily accessible to the public, for the next year as is currently the case with the leadership retreat subdomain? Secondly, why is there no revision log for the Student Life Peace Week page? Yesterday there was no content on the page and today there is, yet there is no revision log and no needs review email was generated. https://student-life.phsc.edu/programs/peace-week

**Comment by boettcc** [comment]
@C13L0 @curtiskphsc - it seems like a missed opportunity to not have these on the student life subdomain site event listing especially if that is where students are looking (and by the page visits, that does appear to be the case). It also seems as through we are pretty far down the path of the event site development at this point. I think we need to create the best possible user experience with what has been done already. Then it may be a good idea to meet afterwards to discuss the way events should be positioned on the site and/or subdomain. From what I know, @jeppy64  build some great features and options into the events section. Maybe users need more training on how to use and maximize those features

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 

The website has been completed and is ready to go live. Do you want the domain to be peace-week@phsc.edu or peaceweek@phsc.edu ?

**Comment by C13L0** [comment]
@curtiskphsc It's a program content type and hasn't been added to moderation yet. You are welcome to create a **new** ticket "Add moderation to program content type".

**Comment by curtiskphsc** [comment]
@C13L0 @boettcc Actually, this is **_not_** all of them. This is mostly West Campus (a few North Campus) The one Laura Raposa created (Porter Campus) simply has text that directs visitors to the new unapproved peace week subdomain. Also, Jessica created a bunch of separate events rather than creating daily events with multiple sessions. Peace Week is a collegewide event last I heard, so we are missing East, Spring Hill, Porter and the rest of North. As far as I am concerned I want nothing to do with the new subdomain as marketing was not brought to the table for discussion as to whether or not a subdomain was needed. I want nothing to do with it. Lucy or Melanie need to make that call.

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 

Please speak with Lucy concerning her conversation with Dr. Harts yesterday. The url https://peaceweek.phsc.edu was approved and the website is live. Kevin, you have full access to edit content and can login at https://peaceweek.phsc.edu/user. You can reset your password by clicking the "Forgot password" link as this website isn't connected to active directory.

Assigning to @curtiskphsc for website review.

**Comment by C13L0** [comment]
@curtiskphsc @boettcc The website has been connected to google analytics =)

**Comment by curtiskphsc** [comment]
@C13L0 As this site is not an official college web property, it was determined in our weekly marketing meeting that we will not be reviewing this content. Therefore, I am unassigning myself per Melanie and Lucy.

**Comment by C13L0** [comment]
Assigning to self to copy site as flat html for archival purposes

**Comment by C13L0** [comment]
completed
