### ISSUE TITLE
Cru (North Campus) Information Request

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#405]
Submitted on Tue, 08/28/2018 - 14:34

Submitted values are:

Full Name
Emery Ailes

Email
ailese@phsc.edu

Phone
3527975035

Campus
North Campus

How can we help?
Dr. Emery Ailes is the Advisor of the North Campus. Please update the record. Thus far we meet on Mondays at 11am in A-157. Thank you

**Comment by curtiskphsc** [comment]
@Computerrat This content is owned and managed by Student Life and Leadership. This request should be routed to the North Campus Student Life Coordinator Sandre Lyons or possibly Laura Raposa as she has been creating the organization officer profiles in the past.

**Comment by Computerrat** [comment]
Please review

**Comment by C13L0** [comment]
@curtiskphsc This ticket hasn't been completed

**Comment by curtiskphsc** [comment]
@C13L0 This is content creation and should be directed to the subdomain/content owner. I will pass this along to student-life.phsc.edu as suggested above. I can only assume they have the ability to make this adjustment as they have done so in the past.

**Comment by curtiskphsc** [comment]
Jessica,
The Webmaster received a request to update some information regarding a club advisor listed on https://student-life.phsc.edu/clubs/cru I am including the information below:


"Submitted on Tue, 08/28/2018 - 14:34

Submitted values are:

Full Name
Emery Ailes

Email
ailese@phsc.edu

Phone
3527975035

Campus
North Campus

How can we help?
Dr. Emery Ailes is the Advisor of the North Campus. Please update the record. Thus far we meet on Mondays at 11am in A-157. Thank you"

It appears that Laura Raposa has been managing most of this content based on content creation records. To edit/add/delete a club advisor login at https://student-life.phsc.edu/user/login and navigate to "Manage Clubs and Organizations"

Additionally, the department hours need be edited to reflect that we are again open on Friday. https://student-life.phsc.edu/department-information

To edit/add department hours login at https://student-life.phsc.edu/user/login and navigate to "Edit Department and Business Hours"

Thank You,
Kevin Curtis

Web Content Manager
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
Phone: 727-816-3159

**Comment by C13L0** [comment]
@curtiskphsc This hasn't been completed

> Campus
> North Campus
> Thus far we meet on Mondays at 11am in A-157. Thank you

**Comment by C13L0** [comment]
@curtiskphsc This is a followup to find out where you are with this request

**Comment by curtiskphsc** [comment]
@C13L0  This has been passed along to the content creator/owner Jessica White, for remedy. If and when an update is supplied, I will provide further comment regarding this ticket. Until such time as I provide further comment it shall remain in open status.

**Comment by curtiskphsc** [comment]
@C13L0 As stated, this was passed along to Jessica White for corrections. Asd they are in the middle of Peace Week, I am extending her the professional courtesy of not bothering her with this again until after. I will provide an update as soon as there is an update to provide.

**Comment by C13L0** [comment]
@curtiskphsc This is a follow-up to find out where you are with this ticket

**Comment by curtiskphsc** [comment]
@C13L0 Sent follow-up email to Sandre Lyons.
"Sandre,

We received the below request from Emery Ailes.

"Dr. Emery Ailes is the Advisor of the North Campus. Please update the record. Thus far we meet on Mondays at 11am in A-157. Thank you"

The club advisor info was in fact updated but the meeting dates and times are still absent on the page. I did forward this to Jessica, but as it is a North Campus club I am hoping you can assist with getting the meeting dates and times added to the page? Currently the CRU page lists only Porter and Spring Hill meeting times and locations https://student-life.phsc.edu/clubs/cru

From the dashboard, click on "Manage Clubs and Organizations" and then locate CRU and select edit. On the edit page select "meeting schedule" (screen shot attached). Be sure to enter all info as this information will also display on the home page of the Student Life subdomain.

Any assistance with this would be greatly appreciated.

Thank You,

Kevin Curtis

Web Content Manager

**Comment by curtiskphsc** [comment]
@C13L0 Ticket completed by the appropriate department/content owner per IMM 1-24 section F.
From: Kevin Curtis
Sent: Monday, October 22, 2018 10:57 AM
To: Sandre Lyons
Subject: Re: CRU North Campus Meeting Times
I see you have the meeting dates entered and the page is in draft mode. Do you want me to publish the page so the meeting dates show on the page?

Kevin
From: Sandre Lyons
Sent: Thursday, October 25, 2018 11:40:40 AM
To: Kevin Curtis
Subject: Re: CRU North Campus Meeting Times
 
Yes please.

Did I enter it in the wrong are or format or something?

Sandre

No, you did a great job actually and I truly appreciate it! When you save the page be sure to select "Needs review"
"Draft" is the default at the bottom of the page. If you don't select "needs review" from the drop down I don't get notified.

Thanks again!
KC
Also received this from Jessica White:
"I also hesitated put the Cru meeting info. up as I do not have an activity form showing me that the meeting location, days and times were approved....another big sticking point.

Just because Dr. Ailes (or any other advisor) shares the info doesn't mean that it is approved.

Thank you!
Jess  :)
Jessica M. White, MS
Director of Student Life & Leadership
Pasco-Hernando State College
o: 727.816.3764
c: 813.748.9202"

**Comment by C13L0** [comment]
Completed
