### ISSUE TITLE
Revisions to data on financial aid front page

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#440]
Hi Cielo;

Here are the changes we would like made to our financial aid front page. 

Change tablet to:

PHSC Foundation Scholarship
Dollars Awarded
$1,096,540
(2017-2018)

Change tablet to:

PHSC Foundation Student Scholarships 
Awarded
1015
(2017-2018)

These changes update the data and also put them in a more cohesive and logical order. Lol.

Sincerely,

Kim Williams
Associate Director-Financial Aid
Pasco-Hernando State College 
10230 Ridge Road
New Port Richey, FL  34654
727.816.3195

**Comment by C13L0** [comment]
@curtiskphsc Please update as requested

**Comment by curtiskphsc** [comment]
@C13L0 This information needs to be verified by The Foundation. I will reach out to them. Also, there appears to be an error in the dollar amount of the first card. Once verified, I will gladly make the adjustments.

**Comment by curtiskphsc** [comment]
This is the response from the Foundation. They will be verifying this information tomorrow, 9-7-18, and this will be addressed at that time.
"Good afternoon,
The numbers provided by Financial Aid are slightly higher than the report we run from Next Gen Scholarship Manager. This is because several awards were made late into the summer term after the 17-18 year was already closed in Next Gen and edits could no longer be made. 
Elizabeth Bobbie is out of the office today and I would feel more comfortable verifying the numbers with her first before we publish. 
Kevin - is it okay if I get back to you on this tomorrow morning once I have a chance to confirm?

Thanks,
Michelle"

Michelle Bullwinkel
Director of Alumni and Donor Relations
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
(727) 816-3212

**Comment by C13L0** [comment]
Completed
