### ISSUE TITLE
Website name/title correction ticket

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#464]
From: PHSC Help Desk Faculty and Staff
Sent: Wednesday, September 19, 2018 10:55 AM
To: Webmaster; Darcy McDowell
Subject: Website name/title correction ticket
 
Currently, chiquita henderson is listed as the ada coordinator under the eoa-ada compliance link on our homepage. this needs to be corrected to reflect my name as the ada coordinator.

https://policies.phsc.edu/policies-and-procedures/policy-statements/eoe-ada-compliance?_ga=2.241424962.1777822678.1537196316-1231881568.1533161336

Darcy McDowell

PHSC Help Desk Support

727-816-3311

helpdesk@phsc.edu

**Comment by curtiskphsc** [comment]
@C13L0 Good Morning Pam,
This request came through the HelpDesk. In it Darcy states she should be listed as the ADA coordinator rather than Chiquita. I am changing it for you, so this is simply an FYI.


"From: PHSC Help Desk Faculty and Staff
Sent: Wednesday, September 19, 2018 10:55 AM
To: Webmaster; Darcy McDowell
Subject: Website name/title correction ticket
Currently, chiquita henderson is listed as the ada coordinator under the eoa-ada compliance link on our homepage. this needs to be corrected to reflect my name as the ada coordinator.
https://policies.phsc.edu/policies-and-procedures/policy-statements/eoe-ada-compliance?_ga=2.241424962.1777822678.1537196316-1231881568.1533161336
Darcy McDowell
PHSC Help Desk Support
727-816-3311
helpdesk@phsc.edu

**Comment by C13L0** [comment]
Completed
