### ISSUE TITLE
BSN January app no longer on website

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#532]
Good morning,

I just received a call from a potential BSN student. The BSN application link for January admissions has disappeared from the website. I was going to republish the form, but this approved form is no longer listed. The form should be available through November 13, 2018. I am not sure what happened to this form and why it is not listed as an approved form so that I can publish it myself.

Please advise, thank you!

Connie Kersey
Admissions and Student Records Specialist
~~~~~~~~~~~~~~~~~~~~~~
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654-5199
727-816-3203 phone
727-816-3389 fax
kerseyc@phsc.edu

**Comment by C13L0** [comment]
From: Webmaster
Sent: Wednesday, October 24, 2018 10:34 AM
To: Chris Bibbo; Connie Kersey; Dave Mayler
Cc: Ryan Truitt; Melissa Harts; Kevin Curtis
Subject: Re: BSN January app no longer on website
 
Good morning,

The BSN application is not showing is because it is scheduled to display from Jan 15, 2019 to Jul 24, 2019. In addition, the document is still in draft and hasn't been approved by the Web Content Manager.

The technical side of the website is working correctly.

Thanks!
Cielo
From: Chris Bibbo
Sent: Wednesday, October 24, 2018 8:55:48 AM
To: Connie Kersey; Dave Mayler; Cielo Johnson; Webmaster
Cc: Ryan Truitt; Melissa Harts; Kevin Curtis
Subject: Re: BSN January app no longer on website
 
Hello Everyone,

I understand that we received a ticket yesterday morning, however the application  is still not published and we have students calling whom would like to enroll. To my count this type of issue has happened over a dozen times in the last year; could somebody please rectify this immediately and let me know how and why this issue keeps occurring or how we can stop it.

Thank you,

Chris

 
Christopher J. Bibbo, J.D., M.S.
Director of Admissions and Student Records
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654-5122
(727) 816-3261 Office
(727) 816-3389 Fax

<img width="476" alt="bsn-application" src="https://user-images.githubusercontent.com/3138019/47438892-5280fd80-d779-11e8-935e-0014de38af1d.png">

<img width="659" alt="bsn-draft" src="https://user-images.githubusercontent.com/3138019/47438904-590f7500-d779-11e8-9dbf-dbf17c4c90b3.png">
